public class MyFirstapexclass 
{
    
    Public static void insertAccount()
    {
        String s;
        s='salesforce';
        System.debug('I am printing sir' +s);
    }
    public static string Collectiontest()
    {
    Set<string> Lst=new Set<String>();
    Lst.add('V');
    Lst.add('I');
    Lst.add('N');
    Lst.add('E');
    Lst.add('E');
    Lst.add('T');
    System.debug(Lst);
    Return 'Vineet';
    }
}